config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: %i[create]
  resources :drawing_songs, only: %i[index show] do
    resources :pictures, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/drawing_song.rb
# == Schema Information
#
# Table name: drawing_songs
#
#  id         :bigint           not null, primary key
#  difficulty :integer
#  lyrics     :string
#  name       :string           not null
#  process    :string
#  song       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_drawing_songs_on_name  (name) UNIQUE
#
class DrawingSong < ApplicationRecord
  has_many :pictures, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id              :bigint           not null, primary key
#  image           :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  drawing_song_id :bigint           not null
#  user_id         :bigint           not null
#
# Indexes
#
#  index_pictures_on_drawing_song_id  (drawing_song_id)
#  index_pictures_on_user_id          (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (drawing_song_id => drawing_songs.id)
#  fk_rails_...  (user_id => users.id)
#
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  belongs_to :drawing_song

  validates :image, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :bigint           not null, primary key
#  crypted_password :string
#  email            :string           not null
#  name             :string           not null
#  salt             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :pictures, dependent: :destroy

  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :name, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :success, :warning, :error
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path
  end
end

app/controllers/drawing_songs_controller.rb
class DrawingSongsController < ApplicationController
  def index
    @drawing_songs = DrawingSong.all.order(:created_at)
  end

  def show
    @drawing_song = DrawingSong.find(params[:id])
    @picture = Picture.new
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def create
    @picture = current_user.pictures.build(picture_params)
    if @picture.save
      redirect_to drawing_songs_path
    else
      redirect_to drawing_songs_path, warning: '保存に失敗しました'
    end
  end

  private

  def picture_params
    params.require(:picture).permit(:image).merge(drawing_song_id: params[:drawing_song_id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[top]

  def top; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to drawing_songs_path, success: t('.success')
    else
      flash.now[:warning] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, success: t('.success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to drawing_songs_path, success: t('.success')
    else
      flash.now[:warning] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drawing_songs/_drawing_song.html.erb
<tr>
  <td class="py-3 px-4">
    <p class="text-black font-bold text-sm lg:text-2xl"><%= drawing_song.name %></p>
  </td>
  <td class="py-3 px-4">
    <p class="text-red-500 font-bold text-sm lg:text-2xl">鬼</p>
  </td>
  <td class="py-3 px-4">
    <%= button_to t('defaults.challenge'), drawing_song_path(drawing_song), method: :get, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded text-sm lg:text-xl' %>
  </td>
</tr>

app/views/drawing_songs/index.html.erb
<div class="container mx-auto text-center py-6 px-4 text-sm lg:text-3xl text-black font-bold">
  <h1><%= t('.list_of_drawing_songs') %></h1>
</div>

<div class="container mx-auto flex flex-col min-h-screen">
  <table class="min-w-full divide-y divide-gray-200">
    <thead>
      <tr>
        <th class="py-2 px-4 text-left text-sm lg:text-xl"><%= DrawingSong.model_name.human %></th>
        <th class="py-2 px-4 text-left text-sm lg:text-xl"><%= DrawingSong.human_attribute_name(:difficulty) %></th>
        <th class="py-2 px-4 text-left text-sm lg:text-xl"></th>
      </tr>
    </thead>
    <tbody class="bg-white divide-y divide-gray-200">
      <% @drawing_songs.each do |drawing_song| %>
        <%= render 'drawing_song', drawing_song: drawing_song %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/drawing_songs/show.html.erb
<div class="bg-white py-6 sm:py-8 lg:py-12 min-h-screen">
  <div class="mx-auto max-w-screen-xl px-4 md:px-8">
    <div class="grid gap-8 md:grid-cols-2 lg:gap-12">
      <div class="relative">
        <div class="overflow-hidden rounded-lg">
          <canvas id="canvas" class="w-full border-4 border-primary"></canvas>
        </div>
        <div class="my-4">
          <input type="radio" id="draw" name="mode" class="radio radio-primary" checked/>
          <label for="draw">ペン</label>
          <input type="radio" id="erase" name="mode" class="radio radio-primary">
          <label for="erase">消しゴム</label>
          <button id="clear" name="mode" class="btn btn-sm btn-outline btn-error">クリア</button>
        </div>
      </div>

      <div class="flex flex-col items-center justify-center md:pt-8">
        <div class="text-center mb-10">
          <p class="text-gray-700">「絵描き歌」を聴き、絵を描いてみましょう！</p>
          <p class="text-gray-700">何も難しくはありません。歌詞の通り描けばいいのです...。</p>
        </div>
        <div class="mt-4 mb-4">
          <%= audio_tag @drawing_song.song ,id: "audio", controls: true, controlslist: 'nodownload' %>
        </div>
        <%= form_with(model: @picture, url: drawing_song_pictures_path(@drawing_song), id: 'picture-form', authenticity_token: true) do |form| %>
          <div class="mt-8">
            <div class="mb-8">
              <div class="text-center mb-4 font-bold">
                <p>何の絵描き歌？</p>
              </div>
              <label for="name" class="block font-medium text-gray-700"><%= t('.guess') %></label>
              <input type="text" id="name" placeholder="未実装" class="block px-4 py-2 border border-gray-300 rounded-md">
            </div>
            <p class="text-gray-700">絵を実際に紙に書いて写真を撮ってアップしてください</p>
            <%= form.file_field :image, id: 'picture_image_data' %>
            <%= form.button t('.decide'), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4", id: 'save-button' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shokenekakiuta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %> %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render 'shared/after_login_header' %>
    <% else %>
      <%= render 'shared/header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_after_login_header.html.erb
<div class="navbar bg-neutral text-neutral-content">
  <div class="flex-1">
    <%= link_to t('defaults.shoken_ekakiuta'), root_path, class: "btn btn-ghost normal-case text-xl" %>
  </div>
  <div class="flex-none gap-2">
    <div class="dropdown dropdown-end">
      <label tabindex="0" class="btn btn-ghost btn-circle avatar">
        <div class="w-10 rounded-full">
          <img src="#" />
        </div>
      </label>
      <ul tabindex="0" class="mt-3 p-2 shadow menu menu-sm dropdown-content bg-base-100 text-black rounded-box w-52">
        <li><%= link_to t('defaults.settings'), '#' %></li>
        <li><%= link_to t('defaults.logout'), logout_path, data: { turbo_method: :delete } %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li class="text-xs "><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% case message_type %>
  <% when 'success'%>
    <div class="alert alert-success">
  <% when 'warning'%>
    <div class="alert alert-warning">
  <% when 'error' %>
    <div class="alert alert-error">
  <% else  %>
    <div class="alert alert-info">
  <% end %>
      <%= message %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-10 bg-neutral text-neutral-content rounded">
  <div class="grid grid-flow-col gap-4">
    <%= link_to t('defaults.terms_of_service'), '#', class: 'link link-hover' %>
    <%= link_to t('defaults.privacy_policy'), '#', class: 'link link-hover' %>
    <%= link_to t('defaults.contact'), '#', class: 'link link-hover' %>
    <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg></a> 
  </div> 
  <div>
    <p>© 2023 初見絵描き歌 - ShokenEkakiuta - </p>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="navbar bg-neutral text-neutral-content">
  <div class="flex-1">
    <%= link_to t('defaults.shoken_ekakiuta'), root_path, class: "btn btn-ghost normal-case text-xl" %>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal px-1">
      <li><%= link_to t('defaults.register'), signup_path %></li>
      <li><%= link_to t('defaults.login'), login_path %></li>
    </ul>
  </div>
</div>

app/views/static_pages/top.html.erb
<div class="hero min-h-screen bg-base-200">
  <div class="hero-content text-center">
    <div class="max-w-md">
      <h1 class="text-7xl font-bold"><%= t('defaults.shoken_ekakiuta') %></h1>
      <p class="py-6">初めて聴く絵描き歌で絵を描いてみよう！</p>
      <%= button_to t('.register_to_get_started'), signup_path, method: :get, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/user_sessions/new.html.erb
<div class="hero min-h-screen bg-base-200">
  <div class="card flex-shrink-0 w-full max-w-sm shadow-2xl bg-base-100">
    <div class="card-body">
      <%= form_with url: login_path, class: "form-control" do |f| %>
        <div class="form-control">
          <%= f.label :email, class: "label" do %>
            <span class="label-text"><%= User.human_attribute_name(:email) %></span>
          <% end %>
          <%= f.email_field :email, placeholder: "email", class: "input input-bordered" %>
        </div>
        <div class="form-control">
          <%= f.label :password, class: "label" do %>
            <span class="label-text"><%= User.human_attribute_name(:password) %></span>
          <% end %>
          <%= f.password_field :password, placeholder: "password", class: "input input-bordered" %>
        </div>
        <div class="form-control mt-6">
          <%= f.submit t('defaults.login') ,class: "btn btn-primary" %>
        </div>
        <label class="label">
          <%= link_to t('.to_register_page'), signup_path, class: "label-text-alt link link-hover" %>
        </label>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="hero min-h-screen bg-base-200">
  <div class="card flex-shrink-0 w-full max-w-sm shadow-2xl bg-base-100">
    <div class="card-body">
      <%= form_with model: @user, class: "form-control" do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-control">
          <%= f.label :name, class: "label" do %>
            <span class="label-text"><%= User.human_attribute_name(:name) %></span>
          <% end %>
          <%= f.text_field :name, placeholder: "name", class: "input input-bordered" %>
        </div>
        <div class="form-control">
          <%= f.label :email, class: "label" do %>
            <span class="label-text"><%= User.human_attribute_name(:email) %></span>
          <% end %>
          <%= f.email_field :email, placeholder: "email", class: "input input-bordered" %>
        </div>
        <div class="form-control">
          <%= f.label :password, class: "label" do %>
            <span class="label-text"><%= User.human_attribute_name(:password) %></span>
          <% end %>
          <%= f.password_field :password, placeholder: "password", class: "input input-bordered" %>
        </div>
        <div class="form-control">
          <%= f.label :password_confirmation, class: "label" do %>
            <span class="label-text"><%= User.human_attribute_name(:password_confirmation) %></span>
          <% end %>
          <%= f.password_field :password_confirmation, class: "input input-bordered" %>
        </div>
        <div class="form-control mt-6">
          <%= f.submit t('defaults.register'), class: "btn btn-primary" %>
        </div>
        <label class="label">
          <%= link_to t('.to_login_page'), login_path, class: "label-text-alt link link-hover" %>
        </label>
      <% end %>
    </div>
  </div>
</div>